### ISSUE TITLE
undeclared type 'TaglistCollection'

### ISSUE THREAD

**Issue by SonntagAfl** [sanjaysinh-Chauhan/SSCTaglistView#7]
Hi,

I tried to use your TaglistView. I did all the steps from your instruction, CocoaPod install, import in Document, and create an outlet. But the outlet doesn't work. The error: "Use of undeclared type 'TaglistCollection'. Im very new in using extern files with cocoa Pods and don't know how to work with it exactly. Did I missed any step?

Thanks

**Comment by sunil-targe** [comment]
Even I'm also facing the same issue. 👎

**Comment by Nishadarora** [comment]
same thing

**Comment by dhaval4gvm** [comment]
I am facing same issue, did anyone found the solution?

**Comment by Yog98428** [comment]
Any one found the solution...
